---
default:
    bcrypt:
        salt: 24y5Hvo6ke8p251n
    libs: ../omniframe/lib
    mojo_app_lib: PnwQuizzing::Control
    mojolicious:
        secrets:
            - 87R6di927OHTk50fFSMy6OMdGI25wPOm
            - OMdGI25wPOm87R6di927OHTk50fFSMy6
        session:
            cookie_name: pnwquizzing_session
    omniframe: ../omniframe
    docs:
        dir: docs
        home_type: md
        home_title: PNW Bible Quizzing Home Page
        home_name: Home Page
    roles:
        - Coach
        - Quizzer
        - Parent
        - Spectator
        - Quizmaster
        - Answer Judge
        - Scorekeeper
        - Statistician
        - Volunteer
        - Board Member
    meet_roles:
        - Coach
        - Parent
        - Spectator
        - Quizmaster
        - Answer Judge
        - Scorekeeper
        - Statistician
        - Volunteer
    email:
        from: PNW Bible Quizzing <contact@pnwquizzing.org>
        active: 0
    base_url: https://pnwquizzing.org
    template:
        email:
            include_path:
                - templates/components
                - templates/emails
    time_zone: America/Los_Angeles
    season_break:
        month: 8
        day: 1
    admins:
optional_include: local/config.yaml
preinclude: ../omniframe/config/app.yaml
