---
preinclude: ../omniframe/config/app.yaml
default:
    bcrypt:
        salt: 24y5Hvo6ke8p251n
    libs: ../omniframe/lib
    mojo_app_lib: PnwQuizzing::Control
    mojolicious:
        secrets:
            - 87R6di927OHTk50fFSMy6OMdGI25wPOm
            - OMdGI25wPOm87R6di927OHTk50fFSMy6
        session:
            cookie_name: pnwquizzing_session
    omniframe: ../omniframe
    captcha:
        width      : 216
        height     : 50
        size       : 20
        ttf        : static/fonts/Roboto/Roboto-Bold.ttf
        rotation   : 7
        x          : 13
        y_base     : 35
        y_rotate   : 100
        noise      : 1000
        background : [ 255, 255, 255 ]
        text_color : [ 'rand(128)', 'rand(128)', 'rand(128)' ]
        noise_color: [ 'rand(128) + 128', 'rand(128) + 128', 'rand(128) + 128' ]
    docs:
        dir       : docs
        home_type : md
        home_title: PNW Bible Quizzing Home Page
        home_name : Home Page
    roles:
        - Quizzer
        - Coach
        - Parent
        - Official
        - Board Member
        - Pastor
        - Volunteer
        - Spectator
    meet_roles:
        - Coach
        - Parent
        - Official
        - Volunteer
        - Spectator
    bibles:
        - NIV
        - [ 'NASB5', 'NASB (1995)'    ]
        - [ 'NASB',  'NASB (Current)' ]
        - ESV
        - AKJV
        - AMP
        - BSB
        - HCSB
        - KJ21
        - KJV
        - NKJV
        - NLT
        - NRSVA
        - RSV
    email:
        from: PNW Bible Quizzing <example@example.org>
    base_url: https://pnwquizzing.org
    template:
        email:
            include_path:
                - templates/components
                - templates/emails
    time_zone: America/Los_Angeles
    season_break:
        month: 8
        day  : 1
    admins:
www:
    logging:
        filter: ~
    email:
        active: 1
optional_include: local/config.yaml
